### ISSUE TITLE
Minilog - unable to resize

### ISSUE THREAD

**Issue by Nillx** [aaronma37/Deathlog#10]
Hello, im not getting any errors but currently im unable to resize the minilog window. Every time i click the 3 lines it goes to a specific size and i cannot make it smaller or resize the windows inside. Only /reload fixes it.

Also it would be nice if there was a way to hide the circular skill icon in the left upper corner, its covering  the top of the name column.

**Comment by aaronma37** [comment]
> Hello, im not getting any errors but currently im unable to resize the minilog window. Every time i click the 3 lines it goes to a specific size and i cannot make it smaller or resize the windows inside. Only /reload fixes it.
> 
> Also it would be nice if there was a way to hide the circular skill icon in the left upper corner, its covering the top of the name column.

Hello! There is a way to hide the icon in your interface options. The resize bug should be fixed as of 12 hrs ago in 0.1.2

**Comment by Nillx** [comment]
Thanks, resizing works fine now. Im unable to find a way to hide this icon 
![image](https://github.com/aaronma37/Deathlog/assets/34476875/8291ec56-1e8f-437a-9a15-45dbf705c6cc)

Also what do you think if letting us filter the levels displayed in the mini death log as well? So its not full with low lvls.

**Comment by aaronma37** [comment]
Added a way to hide icon in 0.1.3; resizing has been fixed.  Minilog does filtering might be added in 0.1.4

**Comment by Nillx** [comment]
Thanks
