### ISSUE TITLE
Deathlog broken

### ISSUE THREAD

**Issue by Azzuri-UK** [aaronma37/Deathlog#101]
The latest update to the classic client seems to have entirely broken deathlog.  It looks like Blizzard added a HardcoreDeaths channel as well as some other changes?

If you are in a guild you get the following error

Message: Frame:RegisterEvent(): Frame:RegisterEvent(): Attempt to register unknown event "CHAT_MSG_GUILD_DEATHS"
Time: Thu Apr  4 10:49:10 2024
Count: 1
Stack: Frame:RegisterEvent(): Frame:RegisterEvent(): Attempt to register unknown event "CHAT_MSG_GUILD_DEATHS"
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface/AddOns/Deathlog/Libs/DeathNotificationLib/DeathNotificationLib.lua"]:1055: in main chunk

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by aaronma37** [comment]
Thanks for the report, planning on updating this weekend
