### ISSUE TITLE
Deaths are no longer being reported.

### ISSUE THREAD

**Issue by Travis-OBrien** [aaronma37/Deathlog#103]
I just pulled the newest patch `1.12` from 16 hours ago, but I'm not seeing any alerts when someone dies. Also, Deathlog Search tab has stopped listing deaths after 04/01/24.

**Comment by aaronma37** [comment]
Hey, are  you sure that the person that died had the addon installed? 0.1.13 just dropped, which forwards blizzards alerts, so it should show regardless now

**Comment by Travis-OBrien** [comment]
I just updated to `0.1.13` and everything is working as expected, thank you! :)

**Comment by aaronma37** [comment]
Awesome! You're welcome!
