### ISSUE TITLE
miniDeathlog - New entries inserted at incorrect position after zoning 

### ISSUE THREAD

**Issue by sHelme** [aaronma37/Deathlog#13]
After zoning (taking a ship from Eastern Kingdoms to Kalimdor, Teleport Moonglade, etc.) new deathlog entries are inserted at an incorrect position.
This causes new entries to not appear at the top of the mini-Deathlog. 
In some cases there is a larger gap of empty entries within the Deathlog. 
![image](https://github.com/aaronma37/Deathlog/assets/60777375/ca06b09a-d5ad-4fef-a0d8-599468e91810)

**Comment by aaronma37** [comment]
merged fix
