### ISSUE TITLE
Requesting golf clap be added as a sound option

### ISSUE THREAD

**Issue by pva-ms** [aaronma37/Deathlog#17]
The current `Applause` option for sound is loud and fulfills its intended purpose but for some days in Azeroth a quieter, more respectful clap is needed. It would be great to have the classic golf clap be added as a sound option to recognize fallen adventurers without interrupting current gameplay as much.

[https://www.myinstants.com/en/instant/golf-clap/](https://www.myinstants.com/en/instant/golf-clap/)

**Comment by aaronma37** [comment]
xD, will add for 0.1.3

**Comment by aaronma37** [comment]
added, will be in 0.1.3
