### ISSUE TITLE
Options to hide minilog "AddonIcon" and more.

### ISSUE THREAD

**Issue by repsejnworb** [aaronma37/Deathlog#18]
I basically want just a box with the table data, no header and no icon.
Please add the following customization options to the `minilog`

- [x] Hide the Skull-icon (top left corner one)
- [x] Hide the title (the entire UI space, allowing for just a list of names)
- [x] Offset the entry-text (With certain font-sizes and fonts the name can get hidden behind the Skull-icon)

**Comment by zulunia** [comment]
This would be great, it would be awesome to remove it or at least just change the layer so it doesnt show up with the UI off for screenshots, I have to close the window and its a bit tedious

Ive tried mucking around with the \Deathlog\Widgets\Minilog\widget.lua but it doesnt seem to effect anything

E:\Games\World of Warcraft\_classic_era_\Interface\AddOns\Deathlog\Widgets\Minilog\widget.lua

![image](https://github.com/aaronma37/Deathlog/assets/602839/4053cc00-dfe1-4aa4-9f7f-6c42754413d1)

**Comment by aaronma37** [comment]
added; will be in 0.1.3

**Comment by repsejnworb** [comment]
Chad 🥂

**Comment by zulunia** [comment]
Thanks for fixing this my OCD is calmed !

> added; will be in 0.1.3
