### ISSUE TITLE
Fonts dont save after game restart

### ISSUE THREAD

**Issue by Megajuaco** [aaronma37/Deathlog#19]
As the titlte says, I change the font and the size but when i close the game and open it again, it "saves" the selection but it shows the default settings when people die, i need to click on "test" so I can get the changes.

**Comment by aaronma37** [comment]
This affects some people and not others.  I haven't been able to reproduce it so if anyone is able to debug, please help or point me in the right direction :)

**Comment by jared-craig** [comment]
The DeathAlert resets for me as well. Font size 12, Friz Quadrata TT.

**Comment by Megajuaco** [comment]
I was using the same font and it keep reseting, I change it and now its saves, I think its that font.
Now when I change the location on the minimpa of the addon button, it reset aswell.

**Comment by nickst0tt** [comment]
I've tried multiple fonts and am still having this issue. If you can tell me how to collect any debug info you need, I can provide it for you.

**Comment by Nillx** [comment]
Yes this is happening to me as well. I have to reapply the font every time i log in. 
![image](https://github.com/aaronma37/Deathlog/assets/34476875/589b4fa2-27b0-4ce9-88fc-836a040c4107)

This are my settings
![image](https://github.com/aaronma37/Deathlog/assets/34476875/dd99163a-9a0b-411a-93cd-78509c4364ca)

**Comment by xIGBClutchIx** [comment]
Interesting it is only an issue on the first login. Doing a quick reload fixes it.

**Comment by aaronma37** [comment]
@xIGBClutchIx @Nillx @jared-craig @Megajuaco Hey, can someone try on master and see if its fixed?

**Comment by xIGBClutchIx** [comment]
> @xIGBClutchIx @Nillx @jared-craig @Megajuaco Hey, can someone try on master and see if its fixed?

It sadly did not. I did a little poking at the code and threw some debug code in before it sets the font. From what I can tell it knows what font it is and where that font is located. As can be seen here:
![O7WkvEpr](https://github.com/aaronma37/Deathlog/assets/975065/094b0523-8516-4cbf-8589-e023c148c327)

**Comment by aaronma37** [comment]
@xIGBClutchIx Thanks for your help! I pushed another commit.  Let me know that fixed it.  Is this bug for both death alerts and the minilog for you?

**Comment by xIGBClutchIx** [comment]
> @xIGBClutchIx Thanks for your help! I pushed another commit. Let me know that fixed it. Is this bug for both death alerts and the minilog for you?

That seems to have done it. I actually had that same idea you had and was just testing it and it works: https://github.com/aaronma37/Deathlog/commit/fd90fe46495e189b312354149453fa46014ae976#diff-e371b5e0f13efbec7edf7c3b8fe5893ec7ececa0bfb7dfeec3d9d1951916d532R180

I overwrote my version and downloaded the master, and everything seems good now including the minilog!

**Comment by Nillx** [comment]
> @xIGBClutchIx Thanks for your help! I pushed another commit. Let me know that fixed it. Is this bug for both death alerts and the minilog for you?

Only death alerts in the middle. Ill try that version too.

**Comment by aaronma37** [comment]
Awesome, thanks for all the help! Will probably release sometime in the next day

**Comment by xIGBClutchIx** [comment]
> Hi, really sorry. I'm still having this issue. Or at least partially.
> 
> 
> 
> Following the update, it seems the font settings aren't initialised for the first alert that pops up but for subsequent alerts the settings have loaded (the font + size are correct).
> 
> 
> 
> I've also noticed the minimap icon is back to the default position following a complete reboot of the client so it seems there's some issue with the configuration that doesn't resolve until a /reload or an alert pops up.

Try the latest version of master for a fix for the first message. Should hopefully fix that up based on my testing.
