### ISSUE TITLE
Minilog - block people unaviable

### ISSUE THREAD

**Issue by Nillx** [aaronma37/Deathlog#21]
Hello, i guess this is intentional? I would love a way to block/ignore people that abuse the addon and spam random levels and msgs...

![image](https://github.com/aaronma37/Deathlog/assets/34476875/2ce3fde6-9595-4581-9871-a76afc185f01)

**Comment by aaronma37** [comment]
Its just unfinished. Will add for 1.5.4 :)

**Comment by aaronma37** [comment]
merged!
