### ISSUE TITLE
[Bug] Deathlog window stops showing deaths

### ISSUE THREAD

**Issue by Starlynk1** [aaronma37/Deathlog#24]
Noticed that after a while, the deathlog window stops showing new deaths. Seems that the log stops appending new deaths once the window gets filled to a certain point. When I check, it usually stops updating after about 15 deaths. You can scroll down and that is all that shows. Reload fixes it and allows updates to happen, but stops again pretty quickly.

**Comment by Starlynk1** [comment]
I think this is a different issue. Not exactly sure how to reproduce the issue. It just stops updating the window even though the announcements are made. I thought it was about 15 death reports, but that doesn't seem the case now that I'm watching it more closely. I do know that when I scroll down, it would show about 15-20 and then I could keep scrolling and there are no names listed. Figured that was just EOF and stopped scrolling, so there may have been a gap like issue 13.

I will keep scrolling down next time and see if it continues further like 13

**Comment by aaronma37** [comment]
Sounds good, let me know if you find out more.  FWIW there is a "test" button in the interface options to help debug

**Comment by aaronma37** [comment]
I think this is resolved, but please re-open if you find that it isnt
