### ISSUE TITLE
Cyrilic font bug in RUru version game

### ISSUE THREAD

**Issue by Scal** [aaronma37/Deathlog#29]
![image](https://github.com/aaronma37/Deathlog/assets/883513/0a02ddeb-b187-4373-9d59-629d23ddd9a9)
![image](https://github.com/aaronma37/Deathlog/assets/883513/2943afe6-c965-4261-aa21-40c472a32ee9)
![image](https://github.com/aaronma37/Deathlog/assets/883513/bb8abb02-f0ba-4f33-a7e3-742368cc737a)

**Comment by aaronma37** [comment]
Hey @Scal , which ttf is this using?

**Comment by Scal** [comment]
These are standard fonts on the Russian client, if you just install the addon. I'm afraid some special check is needed, for example, I saw similar code in LibSharedMedia-3.0.lua, there is something similar there depending on the region of the font

**Comment by Scal** [comment]
@aaronma37

**Comment by aaronma37** [comment]
hmm, I'll look into localization.  There are a couple things that make it particularly difficult to do.  For example, we have to map english names -> npc ids in order to communicate source of death, which was manually done.  Would probably need something similar for all languages

**Comment by Scal** [comment]
it’s not a problem that they are displayed in English, the most annoying thing is the squares (because the font that is used there does not support the Cyrillic alphabet) and the tables (the class names do not fit because of the capital letters of the Cyrillic alphabet in the other font that is used there) It would be nice if just make different fonts, or the ability to switch them

**Comment by Scal** [comment]
Here is my version where I indiscriminately replaced all fonts with Arial N
![image](https://github.com/aaronma37/Deathlog/assets/883513/cf5eaf63-aa3b-4bfd-8c70-8cbde23b1590)
![image](https://github.com/aaronma37/Deathlog/assets/883513/bae28aba-10b9-49ca-b072-30e976e86ea4)

**Comment by Kazlogar** [comment]
Can u drop ur files with font fix plz ?

**Comment by aaronma37** [comment]
https://github.com/aaronma37/Deathlog/commit/dc61502ee748c28f5ad02da3962104f22a42a8ba

@Scal this switches most fonts to arial N. Do they look okay for release? They are the same as you posted in the images.  Not sure why class names have weird vertically alignment
