### ISSUE TITLE
Data Request

### ISSUE THREAD

**Issue by colebaril** [aaronma37/Deathlog#32]
Hi, I'm wondering if you store data from this addon? If so, would it be possible to obtain the data? I am a citizen data analyst and would love to crunch some numbers and produce some nice data viz about HC deaths. Of course I'd cite/list you as co-author where applicable.

**Comment by aaronma37** [comment]
Awesome! I look forward to your work!

here is data for era which should have about 90-100k entries
https://github.com/aaronma37/Deathlog/blob/master/db/db.json

I'll be soliciting for official server data soon.  I'll ping here when I do

**Comment by colebaril** [comment]
Excellent, thank you! Server data would be neat.

**Comment by Nakilon** [comment]
I suppose this dump could be much much bigger today.

**Comment by colebaril** [comment]
> Hello. I suppose this dump could be much much bigger today.  
> 
> @aaronma37 was it you who was posting plot screenshots on reddit? Looks like you've stopped collecting data 5 months ago.

There was a second data dump recently which added a lot of data. I was also posting plots and I also have a short WIP blog post about some basic analysis here: https://colebaril.ca/posts/category/data-analysis/hc_wow/
