### ISSUE TITLE
Minilog Icon still on screen after disabling UI

### ISSUE THREAD

**Issue by bobr3940-2** [aaronma37/Deathlog#74]
I use WoW's built in ability to hide the user interface when I want to take a screenshot.  (I believe it is by pressing ALT-Z).  When I do this the skull icon from the minilog stays on my screen.
![DeathlogIssue](https://github.com/aaronma37/Deathlog/assets/100007685/9d1a2d93-4541-4846-a42c-719284ae674d)

**Comment by aaronma37** [comment]
merged a fix, should show up next release
