### ISSUE TITLE
Deathlog showing minimap button in the middle of screen after update

### ISSUE THREAD

**Issue by Zerodeck** [aaronma37/Deathlog#76]
Deathlog showing minimap button in the middle of screen after update, can't click it or anything to move or get rid of it.

![image](https://github.com/aaronma37/Deathlog/assets/24996534/28badbad-cfe2-4290-838c-e73f33295828)

**Comment by Zerodeck** [comment]
This is new as of today, I saw deathlog had an update earlier before I logged on.  It wasn't there yesterday.

**Comment by aaronma37** [comment]
Thanks for the report; able to reproduce.  It is the minilog icon btw, which I think you have hidden.  If you got into the settings and toggle "Show Skull Icon" you can hide it for now. Otherwise, it should be fixed by next update

**Comment by aaronma37** [comment]
I think this is fixed on master now if you don't mind giving it a shot

**Comment by Zerodeck** [comment]
I do have it hidden yeah, I'm using the addon HidingBar - I just tried to "show skull icon" thing but it didn't work checked/unchecked.  Will check the new master!

**Comment by Zerodeck** [comment]
New master works! ty!
