### ISSUE TITLE
Unknown source_id in database

### ISSUE THREAD

**Issue by LT41** [aaronma37/Deathlog#82]
Hi, I'm working with the db.json file and I've noticed two source_id entries that have no value. These entries are supposed to correlate to the NPC monster that killed the player, for instance id 30 is the monster "Forest Spider". However, there is a "-1" and a "-2" value that have no corresponding monster. 

-1 is shown to have killed over 750 players, and -2 has only one kill.

Is this a known feature of WoW databases? Or is something going wrong in data collection? 

Also do you have plans on releasing an updated database? I'd be very interested in working with it. Thank you

**Comment by aaronma37** [comment]
heyo, I can release that now! 

-1, is a general "not found" id.  I think most of those cases come from DC deaths, but there are also probably some that couldn't be found from a manually created table of npcs that we use.  -2 is drowning, -3 is falling, -4 is fatigue, -5 is fire, -6 is lava, and -7 is slime environment damage

**Comment by aaronma37** [comment]
db2.json has the new data. It might be a slightly different format, but it does have 3-4 times the number entries

**Comment by LT41** [comment]
Thank you, I'm working on something cool, I'll send it to you via discord when it's ready. Cheers
