### ISSUE TITLE
Addon Bricked due to channel password.

### ISSUE THREAD

**Issue by lindenkron** [aaronma37/Deathlog#92]
I'm not sure there's any way around this, but someone has put a password on the channel used by the death log, bricking the addon for everyone on the server.

https://i.imgur.com/EUGmvFL.png

"Please enter a password for hcdeathalertschannel."

**Comment by aaronma37** [comment]
@lindenkron what server is this on? I might be able to post a patch

**Comment by aaronma37** [comment]
Added backup channels; if channel's password is taken, it will go to the next.  Also removed popup

**Comment by lindenkron** [comment]
Stitches EU.
